services:
  name: insider-league-simulation
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insider-app
    volumes:
      - .:/var/www
      - /var/www/vendor
      - /var/www/node_modules
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
    depends_on:
      - redis
    networks:
      - insider-network

  nginx:
    image: nginx:alpine
    container_name: insider-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - insider-network

  redis:
    image: redis:alpine
    container_name: insider-redis
    ports:
      - "6379:6379"
    networks:
      - insider-network

networks:
  insider-network:
    driver: bridge
